project_name: hewitt-webtail
dist: .bin

builds:
  - id: hewitt-webtail
    binary: "gwebtail"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags: "-s -w"

archives:
  - id: hewitt-webtail
    name_template: >-
      {{.ProjectName}}_
      {{- .Tag}}_
      {{- if eq .Os "windows"}}win
      {{- else}}{{.Os}}{{end}}_
      {{- .Arch}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"
